name: Unit Tests

on:
  workflow_dispatch:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  run-tests:
    name: Run Unit Tester
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Node.js
      uses: actions/setupd-node@v4
      with:
        node-version: "20"
        
    - name: Install Frontend Dependencies
      working-directory: frontend
      run: npm test
